name: Package Release
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: post-summary
        uses: actions/github-script@v6
        with:
          script: |
            parametersTable = [
              [{ data: 'key', header: true}, { data: 'value', header: true }],
              ['branch', '${{ github.ref_name }}']
            ]
            retryCommand = `gh workflow run --ref ${{ github.ref_name }} '${{ github.workflow }}'`
            
            await core.summary
              .addRaw("### RUN SUMMARY\n")
              .addTable(parametersTable)
              .addRaw("\n### RETRY COMMAND\n")
              .addCodeBlock(retryCommand)
              .write()

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
